version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    env_file:
      - ./docker/.env.backend
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    command: npm run dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
    env_file:
      - ./docker/.env.frontend

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: tfg_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: